apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: blog
deploy:
  kubectl:
    manifests:
      - infrastructure/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: dntworryjayshere/microservices-app-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: dntworryjayshere/microservices-app-comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: dntworryjayshere/microservices-app-event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: dntworryjayshere/microservices-app-moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: dntworryjayshere/microservices-app-posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: dntworryjayshere/microservices-app-query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
